### ISSUE TITLE
Suggestion: structure the repo to be more amenable to go get. Other suggestions ...

### ISSUE THREAD

**Issue by rolandosegura** [ibm-messaging/mq-golang#1]
Hi,
I think the package is wonderful for Go programmers as a starting point to write Go apps that use MQ.

I'd like to suggest to re-structure the repo to be be more amenable to the go tool.
Currently the package has to be imported as:
import "github.com/ibm/messaging/mq-golang/src/mq"

With the src directory sort of implying a GOPATH. What about removing the src directory and calling the directory for the package ibmmq, or may be just keep the name as mq an call the package mq. Then the import path will match the package name, the import path will look as:
import "github.com/ibm/messaging/mq-golang/mq"

We can go even further to avoid stuttering and rename the repo to golang:

import "github.com/ibm/messaging/golang/mq"

The examples could go, as is conventional, in a separate directory:

github.com/ibm/messaging/golang/mq/   # go source code for package mq
github.com/ibm/messaging/golang/mq/cmd/mqitest/ #source code for demonstration programs.

Another suggestions is to write the comments in a form more conventional to be processed by godoc.

Also as for the design of the package it would be great if it provides higher level concepts, for instance in order to connect to the manager do something like: 

mgr,err := mq.Open("mq://mqserver:1414/channel")

Is there any different process to make contributions to the code on behalf of a company instead that as individual? I work for a company that is an IBM partner and would agree to contribute the code provided that code is contributed on behalf of its name.

Thanks!

**Comment by ibmmqmet** [comment]
Thanks for the comments

I'm happy to remove the "src" element of the directory structure, but I suspect the rest of it can't really be changed due to the overall repository controls and practices set up in our organisation. You'll see the src removal on the next commit. It's a shame that "go test" doesn't seem to like cgo processing in the test modules, otherwise that would simplify some of the structure.

Can you give an example of what you would expect for godoc changes? When I ran the tool, it was giving something that looked reasonable to me.

I'm not fond of the idea of directly having many higher-level concepts in this package. Every time we've tried something like that in other environments, we've had requirements to expose "just one more base feature" and you end up back where you started, only possibly worse off because it wasn't architected. When I started this project, the first version avoided a lot of the MQI details, but once I found I needed to access 3 or 4 options or structure fields for put/get, it became easier to just expose the whole thing. For a much simpler messaging API, I'd be looking at the MQLight packages instead of the general-purpose MQI.

Having said that, I **DO** like the idea of easier handling specifically of the queue manager connection (MQCONN/MQCONNX) verbs. In this current version of the code, there's not a lot of choice - it's a direct connection to a local qmgr, or you could set environment variables such as MQSERVER to drive much of the client setup to a remote qmgr. All I needed for my immediate project was local connectivity, so that's where I started. The Java MQI classes do have several connection constructor methods, including a hashmap-based version passing in named properties like hostname and port. That's perhaps what I would like to add as well as/instead of the full-blown MQCONNX verb with structures pointing to structures containing structures ... 

I've put the question out about external contributions. Will post back here when I get an answer.

**Comment by rolandosegura** [comment]
Hi,

I didn't express myself correct in my comment regarding godoc. What I
intended to say is that would be nice if the package,types and function all
have a leading comment section so that by running godoc one can see the
documentation for all these objects , For an example the functions that
wraps the MQI string mapping functions have only one  "global" comment for
all of them. Also would be nice if the comments are written in the Go's
conventional style as stated in the Commentary section of the Effective Go
document or as suggested by the golint tool (https://github.com/golang/lint).
If you agree I can volunteer to rewrite or add the missing comments as
suggested by golint once we have figured the external contribution aspect.

I can also volunteer to the queue manager connection, in the past I wrote a
function that parses a URL connection and establishes the connection to the
manager using MQCONNX.

Regarding the more general idea of exposing higher level concepts in the
package, probably it could be written as separate package client of this;
or it could be that the same package provides both high level concepts and
also provide access to the raw MQI interface.Once I toyed with the idea
that the object returned by a connection to the manager was smart to keep a
pool of connections for various operations with objects in the manager,
akin to what the Go's stdlib database/sql package does (or net/http); the
idea was that clients of the package were long-lived servers that would be
operating against different objects in the manager (reading from queues ,
writing from queues) , the library itself would provide the amenities of
connection pooling that application hosted WAS get.

Another thing I've been thinking is not to expose directly object of the
MQI C pseudo package like C.MQPMO_SYNCPOINT this way programs like mqitest
are not forced to import the C pseudo package and other Cgo's paraphernalia.

Also what do you think of implementing an error type that wraps the
Completion and Reason Code something along the lines of:

type Error struct {
        Reason int32
        Completion int32
}

func (err *Error) Error() string {
        return fmt.Sprintf("MQCC = %s [%d] MQRC = %s [%d]",
MQCC_STR(err.Completion), err.Completion,MQRC_STR(err.Reason), err.Reason)
}

That way the function/methods don't need to return a MQReturn value and in
the case the client of the package wants to check for specific values of
the CC or RC can inspect the returned error value:

datalen, err = qObject.Get(getmqmd, gmo, l, buffer)
if err != nil {
   msgAvail = false
   fmt.Println(err)
   if err,ok := err.(ibmmq.Error); ok && err.Reason ==
MQRC_NO_MSG_AVAILABLE { ... }
}


Again if you think any of these ideas worth trying I can help implementing
it.

Thanks

**Comment by ibmmqmet** [comment]
Discussions here have centred around what does "contributed on behalf of its name" mean? The simplest solution is for any userid that's submitting changes to be an obvious company-oriented name. Like mine has "ibm" in it. That way it's automatically included. And of course any commit comment could include a reference to a company. Whether that's acceptable to your (or should that be "Your", to do it more like the license docs) organisation, based on the CLA document is something you'd have to sort out.

I don't plan to add anything like connection pooling or session management, but I'd be happy for you to have a go at adding it. 

As you can probably see, there's now been a bunch of changes to the layout and commentary, as well as the removal of cgo requirements from applications. So I'm going to mark this as closed as  I think it has dealt with the majority of the comments.
