### ISSUE TITLE
Fail build if GOOS=linux and GOHOSTOS=windows

### ISSUE THREAD

**Issue by romapres2010** [ibm-messaging/mq-golang#114]
If i try build GOOS=linux and GOHOSTOS=windows
I got err like "undefined: ibmmq.MQQueueManager"

If GOOS=windows and GOHOSTOS=windows - thst is OK.

go env 
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Roman\AppData\Local\go-build
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=D:\Roman\YandexDisk\Проекты\GOLang
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=x86_64-w64-mingw32-gcc.exe
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

github.com/ibm-messaging/mq-golang  4.0.10
Go - 1.12

**Comment by ibmmqmet** [comment]
I'm surprised it even gets as far as that. I'd have expected errors much sooner such as not being able to find cmqc.h from /opt/mqm ...

The package requires the MQ SDK to be available for the platform - header files etc - for the cgo processing. And a suitable C cross-compiler would also have to be available. Not something I'm likely to dig into, but if you get all the pieces working it might be interesting case study.

Otherwise, there is the Docker-based build that you could work with instead.
