### ISSUE TITLE
reset Q Stats

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#125]
Can resetQStats command be used on distributed qmgrs prior to v9?  Right now, it is being used only on z/OS qmgrs.  https://github.com/ibm-messaging/mq-golang/blob/bf7e7cff9e763e5dac432590cf4964b44089ff18/mqmetric/queue.go#L103

**Comment by ibmmqmet** [comment]
The RESET QSTATS PCF command is supported on Distributed platforms, but it's not something I would want to extend use of.  So I've not enabled it in this monitor, As there's no alternatives on z/OS at the moment, at any version, it needed to be there. But I'd still like to remove it if that platform ever gets something better. 

V8 is EOS soon, so all in-service Distributed platforms will have the better pub/sub model

**Comment by salapat11** [comment]
Thanks Mark.  We are in a need of some sort of monitoring for prior v9 and thought this would be an option.  Does it impact performance if used on distributed?

**Comment by ibmmqmet** [comment]
It's not particularly a performance problem. It's just that, as noted several times previously, there's always the possibility of incorrect data being seen because of multiple monitors running simultaneously and each only getting partial data - that has happened to people before and caused much confusion and concern.

**Comment by salapat11** [comment]
Thank you
