### ISSUE TITLE
Data race with endian var

### ISSUE THREAD

**Issue by ravellan** [ibm-messaging/mq-golang#140]
While testing my own code for data races I discovered a data race warning with writes to the `endian` variable in every call to some of the package methods.

**To reproduce**
```
func main() {
	for i := 0; i <= 10; i++ {
		go ibmmq.NewMQCFH()
	}
	time.Sleep(1 * time.Second)
}
```
```
$ go run -race ibmmq_race.go 
==================
WARNING: DATA RACE
Write at 0x00000089ead0 by goroutine 7:
  github.com/ibm-messaging/mq-golang/ibmmq.NewMQCFH()
      /go/src/github.com/ibm-messaging/mq-golang/ibmmq/mqiPCF.go:85 +0x134

Previous write at 0x00000089ead0 by goroutine 8:
  github.com/ibm-messaging/mq-golang/ibmmq.NewMQCFH()
      /go/src/github.com/ibm-messaging/mq-golang/ibmmq/mqiPCF.go:85 +0x134
```
Perhaps `endian` can be set as a constant in respective `cmqc_` file instead?

**Comment by ibmmqmet** [comment]
I don't think this is a real problem is it's always going to be setting the same value (and you shouldn't get a half-set/half-unset field even when 2 threads make the change simultaneously). But there is a better way to have it only set once, via a package init function. I'll make that change for the next update. Thanks for pointing it out.

**Comment by ravellan** [comment]
Thanks for the response. As you say it's probably not a real problem but more of a nuisance if code utilizing the package in multiple go routines not passing tests with -race flag.
Looking forward to the next update.

**Comment by ravellan** [comment]
Tests with -race passes now as they should. Thanks!
