### ISSUE TITLE
Information about application connected in queues

### ISSUE THREAD

**Issue by AlexAlvesJr** [ibm-messaging/mq-golang#153]
Hi, Mark!

Is there anyway that we can monitor or receive/store/display information about application that are connected in each queue and/or channel using this exporter metrics?

For example, we would like to know and have some history of applications and processes that were connected in MQ today or yesterday (name, IP address, channel, queue, etc).

Best regards,
Alex

**Comment by ibmmqmet** [comment]
Not using this metric package. The kind of information you are asking for does not fit naturally into metrics databases - its mostly text for example rather than numbers. 

MQ (on Distributed platforms) is able to produce that data through its [Accounting](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.mon.doc/q037240_.html) events. You can also get it by subscribing to Application Activity Trace events but I'd probably prefer the Accounting for historic recording.

On z/OS it comes from SMF type 116 records which is very different to process, but comparable information.

To format the MQ events once you've enabled them, there are programs like amqsact and amqsevt. The amqsevt sample can emit in JSON format which might be convenient to push into other types of databases.

**Comment by AlexAlvesJr** [comment]
Cool, Mark.

Thanks a lot.
Alex

**Comment by ibmmqmet** [comment]
closing as answered
