### ISSUE TITLE
provide docker-hub image of prometheus wmq monitor?

### ISSUE THREAD

**Issue by davidkarlsen** [ibm-messaging/mq-golang#16]
It would be super-awesome if you could provide a prebuilt dockerhub image for the prometheus wmq exporter. Would imagine it could be interesting for more parties!

**Comment by ibmmqmet** [comment]
I'm not fully convinced by how much effort it would actually save, as I would normally expect the monitor to be running alongside a qmgr rather than as a client (unless the qmgr is on a different platform). And that in turn implies a certain amount of configuration folllowing the patterns and expectations set out by the full MQ docker images. For example, what's the qmgr name, which queues to monitor etc.

What I might think about doing is including just a sample Dockerfile that builds on top of that full MQ image, rather than creating a full standalone image. But it would still likely require the Go code to be compiled locally first to be inserted into an image. (Apart from any technical matters, there are also IBM legal/licensing constraints that apply to some of the things that can be done in these repos.)

But nonetheless, an interesting idea that we'll keep in mind for the future. Will see what interest other people might have in it.

**Comment by davidkarlsen** [comment]
I would of course configure it per deployment - preferrably via environment variables injected - that would be along the lines of https://12factor.net/. It would then work like exporters of prometheus itself: https://hub.docker.com/r/prom/ where the binaries are prebuilt, and the consumers of them can pull the pre-build ones, give runtime configurations, and are up and running fast and smooth w/o having to know the least bit about go - like myself :)

**Comment by davidkarlsen** [comment]
@ibmmqmet WDYT? That sounds like a valid use-case given my updates?

**Comment by ibmmqmet** [comment]
As I said, there are IBM legal/licensing constraints and processes about redistributing other product components, even when the license appears to be sufficiently permissive - so creating a container that contains prometheus client code and all the other things that get dragged in during the build is not as easy as we might want it to be. While some of those processes can be dealt with for full-blown products, it's much harder for this kind of package.
 
So, I will continue to think about including a Dockerfile which would help other people build containers, but I'm not going to distribute a container myself. 

The Dockerfile would have to include obtaining the variant of the MQ client libraries that permit redistribution among all the other components.

**Comment by davidkarlsen** [comment]
Can https://github.com/ibm-messaging/mq-docker be used as a base - it does not seem to have these kind of problems? Also https://docs.docker.com/engine/userguide/eng-image/multistage-build/ might help on this?

**Comment by ibmmqmet** [comment]
While the MQ docker image might form the basic image, using it does not solve the underlying general redistribution legal requirements for other 3rd party components that are not already included in it. Plus it has its own license constraints on redistribution.

**Comment by orngeno** [comment]
Hi 
Can you please suggest me how to monitor MQ using prometheus that is running on docker which is installed on windows 7 professional.
MQ v9 is installed previously in the same installation path where docker has been installed.
And I can perform mqsc commands on docker itself due to same installation path.
So What are the pre-requisites and steps to follow in order to monitor queue manager that is running on remote system using preometheus in windows 7.
I have attached the screen shot which depicts the queue manager creation in docker terminal.
![crtmqm in docker](https://user-images.githubusercontent.com/31848376/30370589-b5eeebc6-9895-11e7-8eb5-30a8fbddb44b.PNG)
