### ISSUE TITLE
Version of MQ 

### ISSUE THREAD

**Issue by bhyatm** [ibm-messaging/mq-golang#28]
is there an older version of this that can be run on a V8.0.04 queue manager 

Mac

**Comment by ibmmqmet** [comment]
No. 

The only V9-unique feature in the base mqi library structures is the CCDTUrl field, and it would be nice if Go had proper conditional compilation so that could be switched in or out based on the version of cmqc.h. But it doesn't, so we can't.

The publications for resource monitoring is only available in the MQ V9 product, so there's no point in trying to make the rest of this repo work with older versions of MQ.
