### ISSUE TITLE
Exporter on v8 zlinux server

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-golang#67]
MQ Version - 8.0.0.9
mq-golang - v3.1.0
Go compiler - go version go1.11 linux/s390x

Trying to run Prometheus exporter on WebSphere MQ for Linux (zSeries 64-bit platform).    Prometheus service starts and immediately fails with an error - MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_NO_MSG_AVAILABLE [2033]

Is the package supported on v8 zLinux servers?

**Comment by ibmmqmet** [comment]
From the README: "note that the monitoring data published by the queue manager is not available before MQ V9"

I've added a version check into the mqmetric package that will appear in a forthcoming push so it will fail with a more specific error message if you attempt to connect to an older qmgr.

**Comment by salapat11** [comment]
Thanks for the update.  Release v3.0.1 was named as "Work with MQ V8", so thought it would work with v8.  Any future plans to make it compatible to work with v8?

**Comment by ibmmqmet** [comment]
That update was referring specifically to being able to use the packages for general application development. That's why there's the comments at the top of the README about version support and how the monitoring is V9 only.

The monitoring packages can only exploit features that are available in the queue managers - and those published resource statistics are only available in MQ V9 (or the MQ Appliance).

**Comment by salapat11** [comment]
Thank you
