### ISSUE TITLE
Missing -rpath in mqi.go LDFLAGS

### ISSUE THREAD

**Issue by yurist** [ibm-messaging/mq-golang#8]
Currently, `LDFLAGS` in mqi.go do not specify `-rpath`:

https://github.com/ibm-messaging/mq-golang/blob/master/ibmmq/mqi.go#L40

MQ docs recommend using `-rpath` for linking, and indeed when it's absent it's a bit painful: the executable can't run unless `LD_LIBRARY_PATH` is set (normally by `source /opt/mqm/bin/setmqenv -sk` or similar). Unfortunately, it doesn't seem to work reliably for services, e.g. trigger monitors.

I am not sure how it can be best addressed. Would just setting 64-bit lib for default MQ installation be better than now? Like

    #cgo !windows LDFLAGS: -L/opt/mqm/lib64 -Wl,-rpath=/usr/lib64 -lmqm_r

I will be probably forking your library to set it for me for the time being, I haven't found another option. Any ideas?

Thanks for your support!

**Comment by ibmmqmet** [comment]
A reasonable change to make, so I've pushed a modified mqi.go. It doesn't do any harm to add that directive.

But personally, I ALWAYS run things like services under a shell script as that is easier to modify to set 
any environment or change command options. It can simplify moving services to run under different queue managers under different installations, as you would not want to rely on the embedded path.

Because the queue manager runs as setuid (to mqm, not to root) programs, environment variables like LD_LIBRARY_PATH are not automatically inherited by services. Instead there is a service.env file that can be used to set values globally for all services.
